backend:
  name: git-gateway

media_folder: assets

collections:
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
    - label: "Site Settings"
      name: "sitesettings"
      file: "info.json"
      delete: false
      fields:
        - {label: "Site Title", name: "title", widget: "string"}
        - {label: "About/Tagline", name: "about", widget: "string"}
        - {label: "Google Analytics", name: "analytics", widget: "string"}
        - label: "Logo"
          name: "logo"
          widget: "image"
          default: "/logo.png"
          media_library:
            config:
              multiple: false
        - label: "Favicon"
          name: "favicon"
          widget: "image"
          media_folder: ../
          default: "/favicon.png"
          media_library:
            config:
              multiple: false
        - label: "Menu"
          name: "menu"
          widget: "list"
          fields:
            - {label: Link title, name: title, widget: string }
            - {label: Link, name: link, widget: string}
